codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    patch:
      default:
        target: 100%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths:
          - "pvpumpingsystem(\w+/)?[^/]+\.py$"
          #- "pvpumpingsystem/*.py"
      tests:
        target: 70%
        paths:
          - "pvpumpingsystem/test/.*"

comment: off
